name: Docker Image CI/CD
on:
  push: 
    branches: [ dev_zeke ]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Build Image
          run: docker build -t ${{ secrets.DOCKER_REPOSITORY }}:latest .
        - name: Login to registry
          run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-shanghai.aliyuncs.com
        - name: Push Image
          run: docker push ${{ secrets.DOCKER_REPOSITORY }}:latest